### ISSUE TITLE
Specify HTTP client pool size?

### ISSUE THREAD

**Issue by enragedginger** [gnarroway/hato#12]
The docs mention that building a reusable client `will give you nice things like persistent connections and connection pooling`. Is there a way to specify a pool size? I want to send all of my requests through a single client, but I don't want to have anymore than say 4 active requests at any given time to a single server. With `clj-http`, I do this by making a connection manager with `:threads` of 4 and `:default-per-route` of 4.

Can I achieve that same functionality with this library?

**Comment by gnarroway** [comment]
Thanks for taking a look at this library. There are some relevant options right at the bottom of the readme: 

```
# Default keep alive for connection pool is 1200 seconds
-Djdk.httpclient.keepalivetimeout=1200

# Default connection pool size is 0 (unbounded)
-Djdk.httpclient.connectionPoolSize=0
```

Note that they will only be read once at startup. Unfortunately the granularity you want does not exist in the underlying HttpClient as far as I am aware. 

A workaround for now would be to build a reusable client per server (or group of servers).

**Comment by enragedginger** [comment]
Yeah, I saw those, but since they're system level properties, they won't work for my use case.
