### ISSUE TITLE
insecure? flag

### ISSUE THREAD

**Issue by AndreaCrotti** [gnarroway/hato#32]
I know in theory it's possible passing the right SSLContext to have a behaviour similar to the insecure? flag in clj-http, but all my attempts so far failed.
I think given it's maybe a common requirement anyway it would be good to have at least documented how to do it, or even better adding an `insecure?` flag that takes care of it?

If anyone can share a code snippet that shows how to do it in clojure I can also open a PR to add the feature if you agree @gnarroway .
Thanks

**Comment by gnarroway** [comment]
Thanks for your interest in this library. I agree that it would be convenient to add that flag, and also that Java SSL config is always a bit painful.

I just poked around to see what it takes.

- The basic SSLContext building block can been seen at https://github.com/gnarroway/hato/blob/master/src/hato/client.clj#L85
- What we want to do is replace `(.getTrustManagers tmf)` with a TrustManager that accepts all server certs.
- To do that, we implement the interface [X509TrustManager](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/X509TrustManager.html) and just do nothing in `checkServerTrusted`

So basically:

```Clojure
; Create the trust manager that accepts everything
(def tm (reify X509TrustManager
          (checkClientTrusted [_ _ _] (println :client-trusted))
          (checkServerTrusted [_ _ _] (println :server-trusted))
          (getAcceptedIssuers [_] (into-array X509Certificate []))))

; Configure the SSLContext with your trust manager
(def ssl-context (doto (SSLContext/getInstance "TLS")
                   (.init nil
                          (into-array TrustManager [tm])
                          (SecureRandom.))))

; Then use that as the `:ssl-context` option to the hato client
```

If you want to provide client certs (e.g. for auth), then that `nil` first argument to the ssl context init will be the key managers, as currently created in the linked source code above.

I'll look at encoding this as a flag but in the meantime the above seems to work.

**Comment by gnarroway** [comment]
I went ahead and added it to 0.9.0-SNAPSHOT. Please try it out [as documented](https://github.com/gnarroway/hato#certificate-authentication)

**Comment by AndreaCrotti** [comment]
Nice thanks!
