### ISSUE TITLE
Decode body on error

### ISSUE THREAD

**Issue by kiranshila** [gnarroway/hato#36]
First off, thanks for the great library! I've been using it as a lightweight client in all my new projects.

I have an application that sometimes throws errors (like a 400) that I need to break apart at runtime. I have the `:as` setting set to `:json` and I'm getting bodies back that are `:content-type "application/json"` but the body isn't getting decoded. Is this something I can enable? I'm using hato with `:async? true` and puts everything on a channel, so I can deal with exceptional behavior in the consumers like so

```clojure
(defn http-request [method url key & [params]]
  (let [chan (a/chan)
        put-close #(do
                     (a/put! chan %)
                     (a/close! chan))]
    (hc/request
     (deep-merge
      {:method method
       :url url
       :as :json
       :async? true
       :headers {"X-API-Key" key}}
      params)
     put-close
     put-close)
    chan))
```

Any help would be appreciated.

**Comment by gnarroway** [comment]
Hi, correct me if I am wrong, but what I think you are saying is that you want json bodies to be transformed on exceptional status codes. 

You have 2 options:

- set `:coerce` to `:always` (default is `:unexceptional`), if you are sure the response body will always be json
- Set `:throw-exceptions?` to false so it will always just return a map (no exceptions) and you can transform the response as desired.

**Comment by kiranshila** [comment]
Ah perfect!, I missed the `:coerce` option. Thanks again!
