### ISSUE TITLE
document connection keepalive and connection limit ?

### ISSUE THREAD

**Issue by henryw374** [gnarroway/hato#37]
i needed to set these and it turns out they are only set-able globally via system props, see

https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.net.http/share/classes/jdk/internal/net/http/ConnectionPool.java#L54

took a while to track down... and tbh if I realised this before I might have chosen to use clj-http instead. could be worth adding to the readme?

**Comment by gnarroway** [comment]
Thanks for raising. Closing this as the options have always been documented ("Other advanced options" at the bottom of the readme). In future I might make it more clear that they can't be set directly per client.
