### ISSUE TITLE
Alternative to httpbin in tests?

### ISSUE THREAD

**Issue by borkdude** [gnarroway/hato#39]
I'm adding compatibility for hato in babashka (a scripting environment for Clojure) so you can use hato from the command line with instant startup.

I adopted the test suite of hato within babashka but when running those, I noticed the tests took extremely long and sometimes failed with a 504 due to httpbin being slow.

Perhaps there is another service that can be used in testing that is more reliable.

**Comment by borkdude** [comment]
I'm also using httpbin to test babashka.curl - perhaps it's just having a bad day.

**Comment by borkdude** [comment]
Seems to have already been resolved.

**Comment by gnarroway** [comment]
Thanks. If need be, we can rewrite some tests to use an internal httpkit server (I think there are already a few). Also I think a few tests already use another public alternative to httpbin due to a bug on their end. Can evaluate based on future flakiness.

**Comment by borkdude** [comment]
I ended up adding this to the end of the tests:

``` clojure
(try (get "https://httpbin.org/gzip" {:timeout 1000})
     (catch java.net.http.HttpTimeoutException _
       (doseq [v (vals (ns-publics *ns*))]
         (when (:integration (meta v))
           (println "Removing test from" v "because httpbin is slow.")
           (alter-meta! v dissoc :test)))))
```

**Comment by borkdude** [comment]
@gnarroway Here is how you can use hato with the new babashka 0.6.7:

``` clojure
(require '[babashka.deps :as deps])

(deps/add-deps
 '{:deps {hato/hato {:mvn/version "0.8.2"}
          borkdude/spartan.spec {:git/url "https://github.com/borkdude/spartan.spec"
                                 :sha "12947185b4f8b8ff8ee3bc0f19c98dbde54d4c90"}}})


(require '[spartan.spec]) ;; defines clojure.spec.alpha
(require '[hato.client :as client])

(prn (:status (client/get "https://clojure.org"))) ;; 200
```

Perhaps an idea to add to the README?

The `spartan.spec` (drop-in replacement for clojure.spec.alpha until it becomes non-alpha) is necessary because spec is loaded here:

https://github.com/gnarroway/hato/blob/ef829066afdaf458dd0299609e20162e65d32380/src/hato/multipart.clj#L5

If those specs were moved to a separate namespace which could be optionally loaded, then this workaround wouldn't be necessary.
