### ISSUE TITLE
Websocket support?

### ISSUE THREAD

**Issue by vincentjames501** [gnarroway/hato#4]
This library looks exactly like what we're looking for! Thanks so much.

Any thoughts on supporting `WebSocket`/`newWebSocketBuilder`?

**Comment by gnarroway** [comment]
Glad you find it useful :) I didn’t need the websocket support myself so was waiting for someone to express interest. Let me play around with it over the coming weeks and see what happens

**Comment by vincentjames501** [comment]
I've been playing with this in PR: #5 

There is no synchronous WebSocket API so closing the WebSocket, sending messages to it later, consuming messages async, etc don't really work well without dropping down to Java's `CompletableFuture` stuff. 

Popular opinion suggests either using something like manifold or core.async.

In my PR I'm using manifold and the API is easy enough to use. It also gives full control of the underlying HttpClient, Listener, and other websocket connection details if needed and even supports low level events like ping/pong for applications that need it.

```clojure 
(require '[manifold.deferred :as d]) 
(require '[manifold.stream :as s]) 
(require '[hato.websocket :as websocket]) 

(let [ws (websocket/websocket "ws://echo.websocket.org")]
  ;; Send a message
  (s/put! ws "Hello")

  ;; Receive a single message
  (println "Message:" @(s/take! ws))

  ;; Receive lots of messages via the helper function
  (ws/consume-msgs ws
                   #(println "Received message:" %)
                   #(println "WebSocket closed!")
                   #(println "There was an error:" %))

  ;; Or roll your own with manifold streams
  (-> (s/consume #(println "Received message:" %) ws)
      (d/finally #(println "WebSocket closed!")))

  ;; You can close the websocket later with
  (Thread/sleep 1000)
  (s/close! ws))
```

**Comment by vincentjames501** [comment]
Complete via #6

**Comment by gnarroway** [comment]
Thanks for your PR. I've adapted it and pushed a snapshot build (0.5.0-SNAPSHOT). Can you please verify that it provides what you need?
