### ISSUE TITLE
Don't always include headers in ex-info

### ISSUE THREAD

**Issue by bowbahdoe** [gnarroway/hato#43]
We have a use case where we pass headers for authorization to a remote service. If we log the hato exceptions we will be leaking secrets in our logs and we kinda want to avoid that if possible.

**Comment by gnarroway** [comment]
Hi, I am going to assume you are talking about exceptions thrown in various status codes, as exceptions thrown for other reasons could be for any reason where you may still need the headers.

So I think there's are several options for you to control this on your own side:

#### 1. Configure the client to not throw exceptions

Set `throw-exceptions?` to false, and then handle the status codes yourself. You can then remove the headers before you throw anything.

#### 2. Modify the middleware stack

There's an example on the [readme](https://github.com/gnarroway/hato#custom-middleware) on providing custom middleware. You could replace the exception throwing one, or add another one that simply removes the headers before they get to the exception throwing one (for the latter case you would have to put it just before, as other middleware require headers to be present).

#### 3. Adjust your logs to process the exception and rethrow a sanitised version

Closing as I don't think a client level option is required at this stage.

**Comment by bowbahdoe** [comment]
We ended up needing to totally wrap hato everywhere to avoid leaking access tokens across the organization. 

```clojure
(ns company.safe-hato
  (:require [hato.client :as hc]
            [hato.middleware :as hm]))

;; Most code copied from hato and tweaked slightly so that we don't
;; need to wrap every usage manually and can just migrate to this ns.

(defn- exceptions-response
  [req {:keys [status] :as resp}]
  (if (hm/unexceptional-status? status)
    resp
    (cond
      (false? (hm/opt req :throw-exceptions))
      resp

      :else
      (throw (ex-info (str "status: " status)
                      (-> resp
                          (update :request dissoc :headers)
                          (dissoc :headers)))))))

(defn safe-wrap-exceptions
  [client]
  (fn
    ([req]
     (exceptions-response req (client req)))
    ([req response raise]
     (client req #(response (exceptions-response req %)) raise))))

(def safe-middleware
  "Middleware which makes it safe to use a hato client with credentials"
  (replace {hm/wrap-exceptions safe-wrap-exceptions}
           hm/default-middleware))

(defn request
  [req & [respond raise]]
  (let [middleware (or (:middleware req) safe-middleware)
        wrapped (hm/wrap-request hc/request* middleware)]
    (if (:async? req)
      (wrapped req (or respond identity) (or raise #(throw %)))
      (wrapped req))))

(defn- configure-and-execute
  [method url & [opts respond raise]]
  (request (merge opts {:request-method method :url url}) respond raise))

(def get (partial configure-and-execute :get))
(def post (partial configure-and-execute :post))
(def put (partial configure-and-execute :put))
(def patch (partial configure-and-execute :patch))
(def delete (partial configure-and-execute :delete))
(def head (partial configure-and-execute :head))
(def options (partial configure-and-execute :options))

(def build-http-client hc/build-http-client)
```

**Comment by bowbahdoe** [comment]
@gnarroway I'm sorry, but i'm still thinking about this.

* Configuring the client to not throw exceptions is a non starter for the same reasons that using monads is a non starter. People forget to check return values.
* Modifying the middleware stack only works per callsite.  Needing to wrap every call-site to not leak credentials in logs just doesn't feel right at all.
* Adjusting the part of the code that catches exceptions at the topmost level is not always doable in a way that isn't insane. If someone logs the exception they get immediately after catching it to rethrow (which people do, constantly) then the only place to handle it is the log appender, which i think would require AOT compiling clojure code/using the jank Java clojure interop in a separate project in order to make a log appender/filter that knows how to inspect an ExceptionInfo properly.

The current situation, where having the request info leak is the default and all the mechanisms to resolve that are opt-out 
and need to be done at every call-site just feels really bad.

**Comment by gnarroway** [comment]
I would be open to PR using a similar throw-entire-message option. Bit annoying that it is breaking but it’s a reasonable argument
